config/routes.rb
Rails.application.routes.draw do
  resources :roles
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }, skip: [:passwords]

  root to: 'posts#index'

  resources :posts, except: [:index]
  get '/accept/:id' => 'posts#accept', as: 'accept'
  get '/export' => 'posts#export', as: 'export'
  get 'books' => 'posts#books'

  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :post_users
  has_many :users, through: :post_users

  validate :content_or_image

  def content_or_image
    errors.add(:error, ': formulario vacío') unless self.content.present? || self.image.attached?
  end

  def content_creator_id
    self.users.where(role_id: 2).first&.id
  end

  def designer_id
    self.users.where(role_id: 3).first&.id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :accept]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.users.push(User.find(current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if update_service
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept
    Facebook.publish(current_user.page_token, @post.content, image_key)
    flash[:success] = "Post with id: #{@post.id} was successfully created in FB!"
    @post.update_attributes(published: true)
    redirect_to root_url
  end

  def export
    @posts = Post.where(published: true)
    if @posts.present?
      respond_to do |format|
        format.pdf do
          render pdf: "Facebook Publications #{Time.now.strftime('%d-%m-%Y')}",
            template: 'pdfs/export.html.haml',
            layout: 'pdf',
            page_size: 'A4',
            lowquality: true,
            orientation: 'Landscape'
        end
      end
    else
      respond_to do |format|
        format.pdf do
          render pdf: "Facebook Publications #{Time.now.strftime('%d-%m-%Y')}",
            template: 'pdfs/no_posts.html.haml',
            layout: 'pdf',
            page_size: 'A4',
            lowquality: true,
            orientation: 'Landscape'
        end
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :image, :user_id)
  end

  def update_service
    Post.transaction do
      @post.update!(post_params)

      post_user_service(@post.content_creator_id) if current_user.is_content_creator?
      post_user_service(@post.designer_id) if current_user.is_designer?
    end
    true
  end

  def post_user(old_user_id)
    @post.post_users.where(user_id: old_user_id)
  end

  def post_user_service(id)
    if id.present?
      @post.post_users.where(user_id: id).first.update_attributes(user_id: current_user.id)
    else
      @post.users.push(User.find(current_user.id))
    end
  end

  def image_key
    @post.image.key if @post.image.attached?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |form|
  = render partial: "devise/shared/error_messages", locals: { resource: post }

  .bg-white.shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.my-2
    - if current_user.is_content_creator?
      .-mx-3.md:flex.mb-6
        .md:w-full.px-3
          = form.label :content, class: 'block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2'
          = form.text_area :content, class: 'appearance-none block w-full bg-grey-lighter text-grey-darker border border-grey-lighter rounded py-3 px-4 mb-3', placeholder: 'Escribe aquí el contenido de la nota', rows: 5, required: true

    - if current_user.is_designer?
      .flex.justify-center.mb-6
        = form.label :image, (fa_icon 'cloud-upload', text: 'Seleccione una Imagen', class: 'fa-2x mb-1'), :class => 'w-64 flex flex-col items-center text-center px-4 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue hover:text-green-300'
        = form.file_field :image, accept: 'image/png, image/gif, image/jpeg', hidden: true, required: true
    .flex.justify-center
      = form.submit("#{button_label} Publicación", id: 'create-post', class: 'text-gray-800 text-sm font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-white hover:bg-green-500 hover:border-green-500 w-1/4')

app/views/posts/_post.html.haml
%td.p-3.px-5.text-justify{class: 'w-2/3'}= post.content
%td.p-3.px-5= image_tag post.image, class: 'w-20' if post.image.attached?
%td.p-3.px-5.text-center= post.id
%td.p-3.px-5.flex.justify-end
  - if can? :show, Post
    = link_to 'Mostrar', post_path(post), class: 'mr-2 text-sm bg-white hover:bg-green-300 border border-gray-500 hover:text-white hover:border-green-300 py-1 px-2 rounded focus:outline-none focus:shadow-outline'
  - if (can? :edit, Post) && !post.published
    = link_to 'Editar', edit_post_path(post), class: 'mr-2 text-sm bg-white hover:bg-orange-300 border border-gray-500 hover:text-white hover:border-orange-300 py-1 px-2 rounded focus:outline-none focus:shadow-outline'
  - if (can? :accept, Post) && !post.published
    = link_to 'Aceptar', accept_path(post), class: 'mr-2 text-sm bg-white hover:bg-green-300 border border-gray-500 hover:text-white hover:border-green-300 py-1 px-2 rounded focus:outline-none focus:shadow-outline'
  - if current_user.is_community_manager? && !post.published
    %button.reject.mr-2.text-sm.bg-white.hover:bg-red-300.border.border-gray-500.hover:text-white.hover:border-red-300.py-1.px-2.rounded.focus:outline-none.focus:shadow-outline{post_id: "#{post.id}", content_creator_id: "#{post.content_creator_id}", designer_id: "#{post.designer_id}"}
      Rechazar
  - if current_user.is_community_manager? && post.published
    %h1 Published

app/views/posts/edit.html.haml
%h1.text-center.text-5xl.mt-24 Editar publicación
= render 'form', post: @post, button_label: 'Editar'
.mb-12
= link_to 'Regresar', root_path, class: 'text-gray-800 text-lg font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-white hover:bg-orange-500 hover:border-orange-500'

app/views/posts/index.html.haml
%h1.text-center.text-5xl.mt-24 Publicaciones
= render partial: "devise/shared/error_messages", locals: { resource: current_user }
.text-gray-900.bg-gray-200.my-8.rounded
  .px-3.py-4.flex.justify-center
    %table.w-full.text-md.bg-white.shadow-md.rounded.mb-4
      %tbody
        %tr.border-b
          %th.text-center.text-xl.p-3.px-5 Contenido
          %th.text-left.text-xl.p-3.px-5 Imagen
          %th.text-center.text-xl.p-3.px-5 Id
          %th.text-xl.p-3.px-5.text-right Opciones
        - @posts.each_with_index do |post, index|
          - color = 'bg-gray-100' if index.modulo(2) === 0
          %tr.border-b.hover:bg-orange-100{class: "#{color}", id: "post_#{post.id}"}
            = render post

app/views/posts/new.html.haml
%h1.text-center.text-5xl.mt-24 Nueva Publicación
= render 'form', post: @post, button_label: 'Crear'
.mb-12
= link_to 'Regresar', root_path, class: 'text-gray-800 text-lg font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-white hover:bg-orange-500 hover:border-orange-500'

app/views/posts/show.html.haml
%h1.text-center.text-5xl.mt-24.mb-4 Mostrar publicación
= render partial: "devise/shared/error_messages", locals: { resource: @post }
.lg:w-full.lg:flex.lg:justify-center.mt-4.mx-auto.mb-8{class: 'sm:w-1/2'}
  - if @post.image.attached?
    .h-48.lg:h-auto.lg:w-48.flex-none.bg-cover.bg-center.rounded-t.lg:rounded-t-none.lg:rounded-l.border.border-gray-300.text-center.overflow-hidden{:style => "background-image: url(#{rails_blob_url(@post.image)})"}
  .border.border-gray-300.bg-white.round.lg:rounded-b-none.lg:rounded-r.p-4.flex.flex-col.justify-between.leading-normal
    .mb-8
      .text-blacky.font-bold.text-xl.mb-2= "Post número: #{@post.id}"
      %p.text-gray-700.text-base= @post.content
    .flex.items-center
      .text-sm
        - content_creator = @post.users.where(role_id: 2).first
        - designer = @post.users.where(role_id: 3).first
        - if content_creator.present?
          %p.text-black.leading-none.italic.font-semibold= "Content creator: #{content_creator.email}"
        - if designer.present?
          %p.text-black.leading-none.mt-2.italic.font-semibold= "Designer: #{designer.email}"
        %p.text-gray-500.font-semibold.mt-4= "Created at: #{@post.created_at.strftime('%d-%m-%Y')}"
        %p.text-gray-500.font-semibold= "Updated at: #{@post.updated_at.strftime('%d-%m-%Y')}"
= link_to 'Regresar', root_path, class: 'text-gray-800 text-lg font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-white hover:bg-orange-500 hover:border-orange-500'
= link_to 'Editar', edit_post_path(@post), class: 'ml-4 text-gray-800 text-lg font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-white hover:bg-orange-300 hover:border-orange-300'