config/routes.rb
Rails.application.routes.draw do
  resources :roles
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }, skip: [:passwords]

  root to: 'posts#index'

  resources :posts, except: [:index]
  get '/accept/:id' => 'posts#accept', as: 'accept'
  get '/export' => 'posts#export', as: 'export'
  get 'books' => 'posts#books'

  mount ActionCable.server => '/cable'
end

app/views/layouts/_navbar.html.haml
.w-full.absolute.top-0
  .bg-gray-200.shadow
    .container.mx-auto.px-4
      .flex.justify-between.py-4
        .div.flex
          = link_to image_tag('logo', class: 'rounded border border-black w-8 hover:border-purple-600 p-1', alt: 'Logo'), root_path
          - if can? :accept, Post
            = link_to 'Administrar Publicaciones', root_path, class: 'text-gray-700  text-lg font-semibold hover:text-purple-600 mx-8'

          - if can? :create, Post
            - if current_user.is_content_creator?
              = link_to 'Contenido', new_post_path, class: 'text-gray-700  text-lg font-semibold hover:text-purple-600 mx-8'
            - if current_user.is_designer?
              = link_to 'Imagen', new_post_path, class: 'text-gray-700  text-lg font-semibold hover:text-purple-600 mx-8'
        .div
          - if can? :manage, Facebook
            - unless current_user.page_token
              = link_to user_facebook_omniauth_authorize_url(), class: 'text-white facebook-color rounded p-2 mr-4' do
                = fa_icon 'facebook-square', text: 'Connect to Facebook'
          - if current_user.is_community_manager?
            = link_to 'Export', export_path(format: :pdf), class: 'text-gray-800 text-sm font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-red-500 hover:border-red-500 mr-2'
          = link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'text-gray-800 text-sm font-semibold border border-gray-500 px-4 py-2 rounded-lg bg-white hover:text-white hover:bg-red-500 hover:border-red-500'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GottaFinishEmAll
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'

  %body
    - if user_signed_in?
      = render 'layouts/navbar'
    #app.container-fluid.mb-8
      = yield

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %title GottaFinishEmAll PDF
    = wicked_pdf_stylesheet_link_tag 'build/tailwind.css'

  %body
    = yield